HopeRegistration/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HopeRegistration.Controllers
{
    public class StudentController : Controller
    {
        Entities.HopeRegistrationNovContext context = new Entities.HopeRegistrationNovContext();
        public IActionResult GetAllStudents()
        {
            List<Models.StudentModel> lst = (from x in context.Students.ToList()
                                             join y in context.Nationalities.ToList() on x.NationalityId equals y.NationalityId
                                             select new Models.StudentModel
                                             {
                                                 FirstName = x.FirstName,
                                                 LastName = x.LastName,
                                                 GenderDisplayName = x.Gender.HasValue ? (x.Gender.Value == true ? "Male" : "Female") : "",
                                                 Mobile = x.Mobile,
                                                 DateOfBirth = x.DateOfBirth,
                                                 StudentId = x.StudentId,
                                                 NationalityId = x.NationalityId.HasValue ? x.NationalityId.Value: -1,
                                                 NationalityName = y.NationalityName,
                                             }).ToList();


            return View(lst);
        }

        public IActionResult AddNewStudent()
        {
            ViewBag.Nationality = context.Nationalities.ToList();
            ViewBag.GradeNumber = context.GradeNumbers.ToList();
            ViewBag.Section = context.SectionNumbers.ToList();

            return View();
        }

        public IActionResult Save(Models.StudentModel studentModel)
        {
            Entities.Student student = new Entities.Student();
            student.FirstName = studentModel.FirstName;
            student.LastName = studentModel.LastName;
            student.DateOfBirth = studentModel.DateOfBirth;
            student.Mobile = studentModel.Mobile;
            student.Gender = studentModel.Gender;
            student.NationalityId = studentModel.NationalityId;

            context.Students.Add(student);
            context.SaveChanges();

            Entities.TeacherStudent teacherStudent  = new Entities.TeacherStudent();
            teacherStudent.StudentId = student.StudentId;
            teacherStudent.GradeNumberId = studentModel.GradeNumberId;
            teacherStudent.SectionNumberId = studentModel.SectionId;
            context.TeacherStudents.Add(teacherStudent);
            context.SaveChanges();



            return RedirectToAction("GetAllStudents");

        }

        public IActionResult UpdateStudent(int Id)
        {
            ViewBag.Nationality = context.Nationalities.ToList();

            var result = context.Students.Where(x => x.StudentId == Id).FirstOrDefault();

            Models.StudentModel studentModel = new Models.StudentModel();

            studentModel.StudentId = result.StudentId;
            studentModel.FirstName = result.FirstName;
            studentModel.LastName = result.LastName;
            studentModel.Mobile = result.Mobile;
            if (result.NationalityId.HasValue)
            {
                studentModel.NationalityId = result.NationalityId.Value;
            }
            studentModel.DateOfBirth = result.DateOfBirth;

            return View (studentModel);

        }


        public IActionResult Update(Models.StudentModel studentModel)
        {

            var result = context.Students.Where(x => x.StudentId == studentModel.StudentId).FirstOrDefault();


            result.FirstName = studentModel.FirstName;
            result.LastName = studentModel.LastName;
            result.Gender = studentModel.Gender;
            result.Mobile = studentModel.Mobile;
            result.DateOfBirth = studentModel.DateOfBirth;
            result.NationalityId = studentModel.NationalityId;

            context.SaveChanges();


            return RedirectToAction("GetAllStudents");
        }

        public IActionResult DeleteStudent(int Id)
        {
            Entities.Student student = new Entities.Student();
            student = context.Students.Where(x => x.StudentId == Id).FirstOrDefault(); 
            context.Students.Remove(student); 
            context.SaveChanges(); 
            

            return RedirectToAction("GetAllStudents");
        }

    }
}

HopeRegistration/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HopeRegistration.Controllers
{
    public class TeacherController : Controller
    {
        Entities.HopeRegistrationNovContext context = new Entities.HopeRegistrationNovContext();

        public IActionResult GetAllTeachers()
        {
            //var listGradeNumbers = context.GradeNumbers.ToList();
           // var ListSectionNumbers = context.SectionNumbers.ToList();
           // var ListTeacher = context.Teachers.ToList();
           // List<int> teacherIds = ListTeacher.Select(x => x.TeacherId).ToList();
          List<Entities.TeacherGradeNumber>  ListTeacherGrader = context.TeacherGradeNumbers.ToList();

            List<Models.TeacherModel> lst = (from x in context.Teachers.ToList()
                                             select new Models.TeacherModel
                                             {
                                                 FirstName = x.FirstName,
                                                 LastName = x.LastName,
                                                 GenderDisplayName = x.Gender.HasValue ? (x.Gender.Value == true ? "Male" : "Female") : "",
                                                 Mobile = x.Mobile,
                                                 HireDate = x.HireDate,
                                                 TeacherId = x.TeacherId,
                                                Education = x.Education,
                                                Salary = x.Salary,
                                                 Subject = x.Subject,
                                                  GradeNumberName = ReturnGradeNumberName(x.TeacherId, ListTeacherGrader),
                                                  SectionName = ReturnSectionName(x.TeacherId, ListTeacherGrader),
                                             }).ToList();


            return View(lst);
        }


        public string ReturnGradeNumberName(int _teacherId, List<Entities.TeacherGradeNumber> data)
        {
           var result = data.Where(x => x.TeacherId == _teacherId).FirstOrDefault();
            if (result != null)
                return context.GradeNumbers.Where(x => x.GradeNumberId == result.GradeNumberId).FirstOrDefault().Name;
            else
            return "";
        }

        public string ReturnSectionName(int _teacherId, List<Entities.TeacherGradeNumber> data)
        {
            var result = data.Where(x => x.TeacherId == _teacherId).FirstOrDefault();
            if (result != null)
                return context.SectionNumbers.Where(x => x.SectionNumberId == result.SectionNumberId).FirstOrDefault().Name;
            else
                return "";
        }

        public IActionResult AddNewTeacher()
        {

            ViewBag.GradeNumber = context.GradeNumbers.ToList();
            ViewBag.Section = context.SectionNumbers.ToList();

            return View();
        }

        public IActionResult Save(Models.TeacherModel model)
        {
            Entities.Teacher teacher = new Entities.Teacher();
            teacher.FirstName = model.FirstName;
            teacher.LastName = model.LastName;
            teacher.HireDate = model.HireDate;
            teacher.Mobile = model.Mobile;
            teacher.Gender = model.Gender;
            teacher.Subject = model.Subject;
            teacher.Salary = model.Salary;
            teacher.Education = model.Education;

            context.Teachers.Add(teacher);
            context.SaveChanges();
 
            Entities.TeacherGradeNumber teacherGradeNumber = new Entities.TeacherGradeNumber();
            teacherGradeNumber.TeacherId = teacher.TeacherId;
            teacherGradeNumber.GradeNumberId = model.GradeNumberId;
            teacherGradeNumber.SectionNumberId = model.SectionId;
            context.TeacherGradeNumbers.Add(teacherGradeNumber);
            context.SaveChanges();


            return RedirectToAction("GetAllTeachers");
        }
    }
}

HopeRegistration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HopeRegistration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header >
        <nav style="background-color: #c1c1c16e !important;"  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:blue">Registration System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="GetAllStudents">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="GetAllTeachers">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="StudentDetails">Student Details</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
          
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HopeRegistration - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HopeRegistration/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HopeRegistration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
          
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>